<script setup lang="ts">
import { ref } from 'vue';
import { onLoad } from '@dcloudio/uni-app';
import { api } from '@/api/index';
const product=ref<any>(null),quantity=ref(1),name=ref(''),contact=ref(''),message=ref(''),consent=ref(false),submitting=ref(false),loading=ref(true),loadFailed=ref(false),productId=ref(0);
onLoad((opt:any)=>{productId.value=Number(opt.id||0);quantity.value=clampQuantity(opt.quantity);loadProduct();});
function clampQuantity(value:unknown){const parsed=Math.floor(Number(value));return Number.isFinite(parsed)?Math.max(1,Math.min(1000000,parsed)):1}
function normalizeQuantity(){quantity.value=clampQuantity(quantity.value)}
function openPrivacyPolicy(){const opener=(uni as any).openPrivacyContract;if(typeof opener==='function'){opener({fail:()=>uni.showModal({title:'隐私保护说明',content:'我们仅使用联系人和联系方式处理本次询价，不用于无关用途。完整指引请在小程序设置中查看。',showCancel:false})});return}uni.showModal({title:'隐私保护说明',content:'我们仅使用联系人和联系方式处理本次询价，不用于无关用途。',showCancel:false})}
async function loadProduct(){if(!productId.value){loading.value=false;loadFailed.value=true;return}loading.value=true;loadFailed.value=false;try{product.value=await api.products.detail(productId.value);message.value=`我想咨询“${product.value.name}”的批量采购价格、起订量和定制方式。`;}catch{product.value=null;loadFailed.value=true}finally{loading.value=false}}
async function submit(){if(!product.value||submitting.value)return;normalizeQuantity();if(!name.value.trim()||!contact.value.trim()||!message.value.trim()){uni.showToast({title:'请填写完整信息',icon:'none'});return}if(!consent.value){uni.showToast({title:'请先阅读并同意隐私保护指引',icon:'none'});return}submitting.value=true;try{const result=await api.inquiries.create({name:name.value.trim(),contact:contact.value.trim(),message:message.value.trim(),products:[{id:product.value.id,quantity:quantity.value}],consent:true});uni.showModal({title:'需求已提交',content:`询价编号 ${result.id}\n工作人员会按您留下的方式联系，请留意电话、微信或邮件。`,confirmText:'知道了',showCancel:false,success:()=>uni.navigateBack()})}catch(error:any){uni.showModal({title:'暂未提交成功',content:error?.data?.message||'网络连接不稳定，请检查后重试。已填写的内容会保留。',confirmText:'继续填写',showCancel:false})}finally{submitting.value=false}}
</script>
<template><view class="page"><view class="state-card" v-if="loading"><view class="skeleton image"></view><view class="state-lines"><view class="skeleton line wide"></view><view class="skeleton line"></view></view></view><view class="state-card failed" v-else-if="loadFailed"><text class="state-title">暂时无法加载商品</text><text class="state-desc">商品可能已下架，或网络连接不稳定</text><button class="retry" hover-class="pressable" @tap="loadProduct">重新加载</button></view><template v-else><view class="product"><image :src="product.coverImage" mode="aspectFill"/><view><text class="name">{{product.name}}</text><text class="price">{{Number(product.price)>0?'参考价 ¥'+Number(product.price).toFixed(2):'企业询价'}}</text></view></view><view class="promise"><text class="promise-title">专人协助选品与报价</text><text class="promise-desc">提交需求后，我们会与您确认数量、预算、定制和交付时间。</text></view><view class="form"><text class="title">采购需求</text><label>联系人<input v-model="name" maxlength="80" placeholder="请填写联系人姓名"/></label><label>联系方式<input v-model="contact" maxlength="100" placeholder="手机、微信或邮箱"/></label><label>预计数量<view class="quantity"><button hover-class="pressable" @tap="quantity=clampQuantity(quantity-1)">−</button><input v-model.number="quantity" type="number" @blur="normalizeQuantity"/><button hover-class="pressable" @tap="quantity=clampQuantity(quantity+1)">＋</button></view><text class="field-hint">可先填写预计数量，最终以确认订单为准</text></label><label>需求说明<textarea v-model="message" maxlength="2000" auto-height placeholder="可补充预算、交付时间、LOGO定制和包装要求"/></label><view class="consent"><text class="box" @tap="consent=!consent">{{consent?'✓':''}}</text><text @tap="consent=!consent">我已阅读并同意</text><text class="privacy-link" @tap="openPrivacyPolicy">《用户隐私保护指引》</text><text @tap="consent=!consent">，用于处理本次询价</text></view><button class="submit" hover-class="pressable" :disabled="submitting" @tap="submit">{{submitting?'正在提交…':'提交询价'}}</button></view></template></view></template>
<style scoped>
.page{min-height:100vh;background:#f4f7f2;padding:24rpx;box-sizing:border-box}.product,.form,.promise,.state-card{background:#fff;border-radius:24rpx;padding:24rpx;box-shadow:0 10rpx 30rpx rgba(37,66,44,.06)}.product{display:flex;gap:20rpx;align-items:center;margin-bottom:20rpx}.product image{width:150rpx;height:150rpx;border-radius:18rpx}.product view{display:flex;flex-direction:column;gap:14rpx;min-width:0}.name{font-size:29rpx;font-weight:700;color:#263122}.price{color:#5f9d46;font-weight:700}.promise{margin-bottom:20rpx;background:linear-gradient(135deg,#eff8ea,#fff)}.promise-title,.promise-desc{display:block}.promise-title{font-size:28rpx;font-weight:800;color:#3f7137}.promise-desc{margin-top:10rpx;font-size:24rpx;line-height:1.6;color:#667263}.form{display:flex;flex-direction:column;gap:25rpx}.title{font-size:34rpx;font-weight:800;color:#253020}label{display:flex;flex-direction:column;gap:12rpx;font-size:26rpx;font-weight:700;color:#34402f}input,textarea{background:#f6f8f5;border:1rpx solid #e2e8df;border-radius:14rpx;padding:20rpx;font-weight:400;box-sizing:border-box}.quantity{display:flex;align-items:center}.quantity button{width:80rpx;height:70rpx;line-height:60rpx;background:#eef4eb;color:#4f7c45;border-radius:14rpx}.quantity input{width:170rpx;text-align:center;margin:0 10rpx}.field-hint{color:#929b8f;font-size:22rpx;font-weight:400}.consent{display:flex;gap:12rpx;color:#6f786c;font-size:23rpx;line-height:1.5}.box{width:34rpx;height:34rpx;border:2rpx solid #6fa458;border-radius:8rpx;color:#5f9d46;text-align:center;line-height:30rpx;flex:none}.submit{background:linear-gradient(135deg,#88bd6f,#5f9d46);color:#fff;border-radius:999rpx;font-weight:800;box-shadow:0 10rpx 24rpx rgba(71,132,57,.2)}.state-card{display:flex;align-items:center;gap:22rpx}.state-card.failed{flex-direction:column;text-align:center;padding:80rpx 30rpx}.state-title{font-size:30rpx;font-weight:800;color:#2e392a}.state-desc{font-size:24rpx;color:#7c8678}.retry{margin-top:16rpx;background:#5f9d46;color:#fff;border-radius:999rpx;font-size:26rpx}.state-lines{flex:1}.skeleton{background:linear-gradient(90deg,#edf1ea 25%,#f8faf7 50%,#edf1ea 75%);background-size:200% 100%;animation:shimmer 1.4s infinite}.skeleton.image{width:150rpx;height:150rpx;border-radius:18rpx}.skeleton.line{height:26rpx;border-radius:10rpx;margin:18rpx 0;width:60%}.skeleton.line.wide{width:90%}@keyframes shimmer{from{background-position:200% 0}to{background-position:-200% 0}}
.privacy-link{color:#4f843f;font-weight:700}
</style>
