<script setup lang="ts">
import { ref } from 'vue';
import { onLoad } from '@dcloudio/uni-app';
import { api } from '@/api/index';
const product = ref<any>(null); const quantity = ref(1); const name = ref(''); const contact = ref(''); const message = ref(''); const consent = ref(false); const submitting = ref(false);
onLoad(async (opt:any)=>{ if(!opt.id)return; quantity.value=Math.max(1,Number(opt.quantity)||1); try{product.value=await api.products.detail(Number(opt.id));message.value=`我想咨询“${product.value.name}”的批量采购价格、起订量和定制方式。`;}catch{uni.showToast({title:'产品已下架',icon:'none'})} });
async function submit(){if(!product.value||submitting.value)return;if(!name.value.trim()||!contact.value.trim()||!message.value.trim()){uni.showToast({title:'请填写完整信息',icon:'none'});return}if(!consent.value){uni.showToast({title:'请同意用于本次业务联系',icon:'none'});return}submitting.value=true;try{const r=await api.inquiries.create({name:name.value,contact:contact.value,message:message.value,products:[{id:product.value.id,quantity:quantity.value}],consent:true});uni.showModal({title:'提交成功',content:`询价编号 ${r.id}，工作人员会尽快联系您。`,showCancel:false,success:()=>uni.navigateBack()})}catch(e:any){uni.showToast({title:e?.data?.message||'提交失败，请稍后重试',icon:'none'})}finally{submitting.value=false}}
</script>
<template><view class="page"><view class="product" v-if="product"><image :src="product.coverImage" mode="aspectFill"/><view><text class="name">{{product.name}}</text><text class="price">{{Number(product.price)>0?'参考价 ¥'+Number(product.price).toFixed(2):'企业询价'}}</text></view></view><view class="form"><text class="title">采购需求</text><label>联系人<input v-model="name" maxlength="80" placeholder="请填写联系人姓名"/></label><label>联系方式<input v-model="contact" maxlength="100" placeholder="手机、微信或邮箱"/></label><label>数量<view class="quantity"><button @tap="quantity=Math.max(1,quantity-1)">−</button><input v-model.number="quantity" type="number"/><button @tap="quantity++">＋</button></view></label><label>需求说明<textarea v-model="message" maxlength="2000" auto-height/></label><view class="consent" @tap="consent=!consent"><text class="box">{{consent?'✓':''}}</text><text>同意酷礼工坊使用以上信息联系我处理本次询价</text></view><button class="submit" :disabled="submitting" @tap="submit">{{submitting?'提交中…':'提交询价'}}</button></view></view></template>
<style scoped>.page{min-height:100vh;background:#f5f7f3;padding:24rpx}.product,.form{background:#fff;border-radius:22rpx;padding:24rpx}.product{display:flex;gap:20rpx;align-items:center;margin-bottom:20rpx}.product image{width:150rpx;height:150rpx;border-radius:16rpx}.product view{display:flex;flex-direction:column;gap:14rpx}.name{font-size:29rpx;font-weight:700}.price{color:#5f9d46}.form{display:flex;flex-direction:column;gap:25rpx}.title{font-size:34rpx;font-weight:800}label{display:flex;flex-direction:column;gap:12rpx;font-size:26rpx;font-weight:700}input,textarea{background:#f6f8f5;border:1rpx solid #e2e8df;border-radius:14rpx;padding:20rpx;font-weight:400}.quantity{display:flex;align-items:center}.quantity button{width:80rpx;height:70rpx;line-height:60rpx;background:#eef4eb;color:#4f7c45}.quantity input{width:150rpx;text-align:center;margin:0 10rpx}.consent{display:flex;gap:12rpx;color:#6f786c;font-size:23rpx;line-height:1.5}.box{width:34rpx;height:34rpx;border:2rpx solid #6fa458;border-radius:8rpx;color:#5f9d46;text-align:center;line-height:30rpx;flex:none}.submit{background:linear-gradient(135deg,#88bd6f,#5f9d46);color:#fff;border-radius:999rpx;font-weight:700}</style>
