const $=s=>document.querySelector(s); let token=sessionStorage.getItem('kuli_staff_token')||''; let me=null;
async function api(path,options={}){const headers={...(options.headers||{}),...(token?{Authorization:'Bearer '+token}:{})};if(options.body&&!(options.body instanceof FormData))headers['Content-Type']='application/json';const r=await fetch(path,{...options,headers});const body=await r.json().catch(()=>({}));if(!r.ok)throw new Error(Array.isArray(body.message)?body.message.join('；'):body.message||'操作失败');return body}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function boot(){if(!token)return;try{me=await api('/api/admin/me');$('#login').hidden=true;$('#app').hidden=false;$('#welcome').textContent=`${me.name} · ${me.role==='owner'?'管理员':'产品编辑'}`;document.querySelectorAll('.owner-only').forEach(x=>x.hidden=me.role!=='owner');await loadProducts()}catch{logout()}}
function logout(){token='';me=null;sessionStorage.removeItem('kuli_staff_token');$('#app').hidden=true;$('#login').hidden=false}
$('#login-form').onsubmit=async e=>{e.preventDefault();$('#login-error').textContent='';try{const d=Object.fromEntries(new FormData(e.target));const r=await api('/api/admin/login',{method:'POST',body:JSON.stringify(d)});token=r.token;sessionStorage.setItem('kuli_staff_token',token);await boot()}catch(x){$('#login-error').textContent=x.message}}
$('#logout').onclick=logout;
document.querySelectorAll('.nav').forEach(b=>b.onclick=async()=>{document.querySelectorAll('.nav').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.view').forEach(x=>x.hidden=true);$('#'+b.dataset.view).hidden=false;$('#title').textContent=b.textContent;if(b.dataset.view==='products')await loadProducts();if(b.dataset.view==='inquiries')await loadInquiries();if(b.dataset.view==='staff')await loadStaff()});
async function loadProducts(){const r=await api('/api/admin/products');$('#product-list').innerHTML=r.items.length?r.items.map(p=>`<article class="card"><img class="thumb" src="${esc(p.coverImage)}"><div class="grow"><b>${esc(p.name)}</b><div class="muted">${Number(p.price)>0?'￥'+Number(p.price).toFixed(2):'询价'} · 更新于 ${new Date(p.updatedAt).toLocaleString()}</div></div><span class="badge ${p.isActive?'':'off'}">${p.isActive?'已上架':'草稿'}</span><button class="secondary edit" data-id="${p.id}">编辑</button>${me.role==='owner'?`<button class="danger off" data-id="${p.id}">下架</button>`:''}</article>`).join(''):'<div class="card">暂无产品，点击“上传产品”开始。</div>';document.querySelectorAll('.edit').forEach(b=>b.onclick=()=>editProduct(r.items.find(p=>p.id==b.dataset.id)));document.querySelectorAll('.off').forEach(b=>b.onclick=async()=>{if(!confirm('确定下架该产品？产品资料会保留。'))return;await api('/api/products/'+b.dataset.id,{method:'DELETE'});loadProducts()})}
function editProduct(p={price:0,stock:0,isActive:false,isRecommended:false}){const f=$('#product-form');f.reset();for(const [k,v]of Object.entries(p)){if(!f.elements[k])continue;if(f.elements[k].type==='checkbox')f.elements[k].checked=!!v;else f.elements[k].value=Array.isArray(v)?v.join(','):v??''}$('#product-error').textContent='';$('#product-dialog').showModal()}
$('#new-product').onclick=()=>editProduct();$('#close-dialog').onclick=$('#cancel-dialog').onclick=()=>$('#product-dialog').close();
$('#cover-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;$('#upload-status').textContent='上传中…';try{const fd=new FormData();fd.append('file',file);const r=await api('/api/upload',{method:'POST',body:fd});$('#product-form').elements.coverImage.value=r.url;$('#upload-status').textContent='上传完成'}catch(x){$('#upload-status').textContent=x.message}}
$('#product-form').onsubmit=async e=>{e.preventDefault();const f=e.target,d=Object.fromEntries(new FormData(f));const id=d.id;delete d.id;d.price=Number(d.price);d.stock=Number(d.stock||0);d.tags=d.tags?d.tags.split(/[,，]/).map(x=>x.trim()).filter(Boolean):[];d.images=[d.coverImage];d.detailImages=[d.coverImage];d.sellingPoints=[];d.isActive=f.elements.isActive.checked;d.isRecommended=f.elements.isRecommended.checked;try{await api('/api/products'+(id?'/'+id:''),{method:id?'PUT':'POST',body:JSON.stringify(d)});$('#product-dialog').close();loadProducts()}catch(x){$('#product-error').textContent=x.message}}
async function loadInquiries(){const r=await api('/api/admin/inquiries');$('#inquiry-list').innerHTML=r.items.length?r.items.map(x=>`<article class="card"><div class="grow"><b>${esc(x.name)} · ${esc(x.contact)}</b><div>${esc(x.message)}</div><div class="muted">${x.products.map(p=>esc(p.name)+' × '+p.quantity).join('；')} · ${new Date(x.createdAt).toLocaleString()}</div></div><select class="lead-status" data-id="${x.id}"><option value="new">新询价</option><option value="contacted">已联系</option><option value="closed">已完成</option></select></article>`).join(''):'<div class="card">暂无客户询价。</div>';document.querySelectorAll('.lead-status').forEach(s=>{s.value=r.items.find(x=>x.id==s.dataset.id).status;s.onchange=()=>api('/api/admin/inquiries/'+s.dataset.id,{method:'PUT',body:JSON.stringify({status:s.value})})})}
async function loadStaff(){const r=await api('/api/admin/staff');$('#staff-list').innerHTML=r.map(x=>`<article class="card"><div class="grow"><b>${esc(x.name)}</b><div class="muted">${esc(x.username)} · ${x.role==='owner'?'管理员':'产品编辑'}</div></div><span class="badge ${x.active?'':'off'}">${x.active?'可登录':'已停用'}</span>${x.role==='editor'?`<button class="secondary toggle-staff" data-id="${x.id}" data-active="${!x.active}">${x.active?'停用':'启用'}</button>`:''}</article>`).join('');document.querySelectorAll('.toggle-staff').forEach(b=>b.onclick=async()=>{await api('/api/admin/staff/'+b.dataset.id,{method:'PUT',body:JSON.stringify({active:b.dataset.active==='true'})});loadStaff()})}
$('#staff-form').onsubmit=async e=>{e.preventDefault();try{await api('/api/admin/staff',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});e.target.reset();loadStaff()}catch(x){alert(x.message)}};
$('#password-form').onsubmit=async e=>{e.preventDefault();$('#password-error').textContent='';try{await api('/api/admin/password',{method:'PUT',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});alert('密码已修改，请重新登录');logout()}catch(x){$('#password-error').textContent=x.message}};
boot();
