export const demoCategories = [
  { id: 1, name: '家用电器', icon: '' },
  { id: 2, name: '商务小电', icon: '' },
  { id: 3, name: '生活电器', icon: '' },
  { id: 4, name: '个护清洁', icon: '' },
  { id: 5, name: '运动户外', icon: '' },
  { id: 6, name: '服饰箱包', icon: '' },
  { id: 7, name: '办公用品', icon: '' },
  { id: 8, name: '数码产品', icon: '' },
  { id: 9, name: '汽车用品', icon: '' },
  { id: 10, name: '母婴玩具', icon: '' },
  { id: 11, name: '医疗保健', icon: '' },
  { id: 12, name: '收藏工艺', icon: '' },
];

export const demoQuickEntries = [
  { name: '新品上市', keyword: '新品', icon: '新' },
  { name: '本周更新', keyword: '更新', icon: '更' },
  { name: '商务文创', keyword: '商务', icon: '文' },
  { name: '茶具厨具', keyword: '茶具', icon: '茶' },
  { name: '独家包销', keyword: '包销', icon: '包' },
  { name: '京东自营', keyword: '自营', icon: '京' },
  { name: '促销赠品', keyword: '促销', icon: '促' },
  { name: '专享特惠', keyword: '特惠', icon: '惠' },
  { name: '知名品牌', keyword: '品牌', icon: '牌' },
  { name: '一件代发', keyword: '代发', icon: '发' },
];

export const demoProducts = [
  {
    id: 101,
    categoryId: 1,
    name: '智能恒温电热水壶礼盒',
    description: '适合员工福利、节庆礼赠和客户拜访，支持企业 LOGO 与礼盒包装。',
    price: 168,
    originalPrice: 239,
    coverImage: '/static/products/zk-01.jpg',
    images: ['/static/products/zk-01.jpg'],
    stock: 500,
    sales: 268,
    specs: [
      { name: '颜色', values: ['米白', '深灰'] },
      { name: '包装', values: ['普通装', '礼盒装'] },
    ],
    tags: ['精选', '可定制'],
    shareTitle: '智能恒温电热水壶礼盒',
    shareDesc: '品质好礼，适合企业批量采购。',
  },
  {
    id: 102,
    categoryId: 2,
    name: '桌面无线蓝牙音箱套装',
    description: '桌搭、会议伴手礼和品牌活动都适合，支持礼盒与卡片定制。',
    price: 129,
    originalPrice: 189,
    coverImage: '/static/products/zk-02.jpg',
    images: ['/static/products/zk-02.jpg'],
    stock: 300,
    sales: 156,
    specs: [{ name: '颜色', values: ['白色', '黑色', '绿色'] }],
    tags: ['商务小电', '礼盒'],
    shareTitle: '桌面无线蓝牙音箱套装',
    shareDesc: '轻巧实用，适合活动礼品。',
  },
  {
    id: 103,
    categoryId: 3,
    name: '便携迷你折叠风扇',
    description: '夏季活动、展会派发和员工福利高频款，单价友好。',
    price: 39,
    originalPrice: 59,
    coverImage: '/static/products/zk-03.jpg',
    images: ['/static/products/zk-03.jpg'],
    stock: 1000,
    sales: 420,
    specs: [{ name: '颜色', values: ['果绿', '奶黄', '樱粉'] }],
    tags: ['夏季专区', '高性价比'],
    shareTitle: '便携迷你折叠风扇',
    shareDesc: '清凉实用，适合批量采购。',
  },
  {
    id: 104,
    categoryId: 4,
    name: '旅行便携剃须刀礼盒',
    description: '适合男士商务礼、员工福利和客户回访，支持外盒定制。',
    price: 89,
    originalPrice: 129,
    coverImage: '/static/products/zk-04.jpg',
    images: ['/static/products/zk-04.jpg'],
    stock: 260,
    sales: 98,
    specs: [{ name: '版本', values: ['基础款', '升级款'] }],
    tags: ['个护清洁', '现货'],
    shareTitle: '旅行便携剃须刀礼盒',
    shareDesc: '小巧实用，出行友好。',
  },
  {
    id: 105,
    categoryId: 5,
    name: '户外运动随行礼包',
    description: '组合运动毛巾、水杯和收纳袋，适合赛事活动和客户关怀。',
    price: 118,
    originalPrice: 168,
    coverImage: '/static/products/zk-05.jpg',
    images: ['/static/products/zk-05.jpg'],
    stock: 260,
    sales: 98,
    specs: [{ name: '套装', values: ['基础套装', '升级套装'] }],
    tags: ['运动户外', '礼盒'],
    shareTitle: '户外运动随行礼包',
    shareDesc: '适合活动礼赠和运动赛事。',
  },
  {
    id: 106,
    categoryId: 6,
    name: '轻商务双肩包定制款',
    description: '通勤、展会、员工入职礼包适用，支持企业标识和批量交付。',
    price: 168,
    originalPrice: 239,
    coverImage: '/static/products/zk-06.jpg',
    images: ['/static/products/zk-06.jpg'],
    stock: 300,
    sales: 156,
    specs: [{ name: '颜色', values: ['黑色', '深灰', '藏蓝'] }],
    tags: ['企业采购', '箱包'],
    shareTitle: '轻商务双肩包定制款',
    shareDesc: '适合企业活动和员工福利。',
  },
  {
    id: 107,
    categoryId: 7,
    name: '办公桌面文具组合',
    description: '会议、培训、入职礼包常用，适合印制品牌标识。',
    price: 56,
    originalPrice: 86,
    coverImage: '/static/products/zk-07.jpg',
    images: ['/static/products/zk-07.jpg'],
    stock: 800,
    sales: 310,
    specs: [{ name: '组合', values: ['三件套', '五件套'] }],
    tags: ['办公用品', '可印刷'],
    shareTitle: '办公桌面文具组合',
    shareDesc: '实用办公好礼。',
  },
  {
    id: 108,
    categoryId: 8,
    name: '快充移动电源礼盒',
    description: '数码礼品热销款，适合会议伴手礼和积分兑换。',
    price: 136,
    originalPrice: 199,
    coverImage: '/static/products/zk-08.jpg',
    images: ['/static/products/zk-08.jpg'],
    stock: 420,
    sales: 236,
    specs: [{ name: '容量', values: ['10000mAh', '20000mAh'] }],
    tags: ['数码产品', '热销'],
    shareTitle: '快充移动电源礼盒',
    shareDesc: '出行刚需，企业礼赠常备。',
  },
];

export const demoUser = {
  id: 420037,
  openid: 'demo_openid',
  nickname: '企业选品账号',
  phone: '136****2694',
  avatar: '',
  points: 0,
  level: '企业会员',
  cartCount: 0,
  favoriteCount: 0,
  footprintCount: 1,
};

export function getDemoProduct(id: number) {
  return demoProducts.find((item) => item.id === id) || demoProducts[0];
}
