export const demoCategories = [
  { id: 1, name: '家用电器', icon: '' },
  { id: 2, name: '商务小电', icon: '' },
  { id: 3, name: '生活电器', icon: '' },
  { id: 4, name: '个护清洁', icon: '' },
  { id: 5, name: '运动户外', icon: '' },
  { id: 6, name: '服饰箱包', icon: '' },
  { id: 7, name: '办公用品', icon: '' },
  { id: 8, name: '数码产品', icon: '' },
  { id: 9, name: '汽车用品', icon: '' },
  { id: 10, name: '母婴玩具', icon: '' },
  { id: 11, name: '医疗保健', icon: '' },
  { id: 12, name: '收藏工艺', icon: '' },
];

export const demoQuickEntries = [
  { name: '新品上市', keyword: '新品', icon: '新', image: '/static/products/zk-03.jpg' },
  { name: '本周更新', keyword: '更新', icon: '更', image: '/static/products/zk-08.jpg' },
  { name: '商务文创', keyword: '商务', icon: '文', image: '/static/products/zk-07.jpg' },
  { name: '茶具厨具', keyword: '茶具', icon: '茶', image: '/static/products/zk-05.jpg' },
  { name: '独家包销', keyword: '包销', icon: '包', image: '/static/products/zk-06.jpg' },
  { name: '京东自营', keyword: '自营', icon: '京', image: '/static/products/zk-01.jpg' },
  { name: '促销赠品', keyword: '促销', icon: '促', image: '/static/products/zk-09.jpg' },
  { name: '专享特惠', keyword: '特惠', icon: '惠', image: '/static/products/zk-02.jpg' },
  { name: '知名品牌', keyword: '品牌', icon: '牌', image: '/static/products/zk-10.jpg' },
  { name: '一件代发', keyword: '代发', icon: '发', image: '/static/products/zk-04.jpg' },
];

export const demoProducts = [
  {
    id: 101,
    categoryId: 2,
    name: '北大荒坚果礼盒',
    description: '坚果礼盒适合节庆福利、客户拜访和企业团购，按采购数量报价。',
    price: 0,
    originalPrice: undefined,
    coverImage: '/static/products/zk-01.jpg',
    images: ['/static/products/zk-01.jpg'],
    stock: 0,
    sales: 0,
    specs: [{ name: '采购方式', values: ['企业询价', '批量采购'] }],
    tags: ['食品礼盒', '待报价'],
    shareTitle: '北大荒坚果礼盒',
    shareDesc: '食品礼盒精选，适合企业福利采购。',
  },
  {
    id: 102,
    categoryId: 2,
    name: '费列罗巧克力礼盒',
    description: '巧克力礼盒适合商务伴手礼、节庆慰问和客户答谢。',
    price: 0,
    originalPrice: undefined,
    coverImage: '/static/products/zk-02.jpg',
    images: ['/static/products/zk-02.jpg'],
    stock: 0,
    sales: 0,
    specs: [{ name: '采购方式', values: ['企业询价', '批量采购'] }],
    tags: ['商务小礼', '礼盒'],
    shareTitle: '费列罗巧克力礼盒',
    shareDesc: '商务礼盒精选，适合批量采购。',
  },
  {
    id: 103,
    categoryId: 2,
    name: '清远鸡礼盒',
    description: '生鲜礼盒适合员工福利、节日慰问和客户关怀。',
    price: 0,
    originalPrice: undefined,
    coverImage: '/static/products/zk-03.jpg',
    images: ['/static/products/zk-03.jpg'],
    stock: 0,
    sales: 0,
    specs: [{ name: '采购方式', values: ['企业询价', '批量采购'] }],
    tags: ['生鲜滋补', '礼盒'],
    shareTitle: '清远鸡礼盒',
    shareDesc: '生鲜礼盒精选，适合节庆福利。',
  },
  {
    id: 104,
    categoryId: 4,
    name: '舒适床品套件',
    description: '床品套件适合员工福利、乔迁礼赠和积分兑换。',
    price: 0,
    originalPrice: undefined,
    coverImage: '/static/products/zk-04.jpg',
    images: ['/static/products/zk-04.jpg'],
    stock: 0,
    sales: 0,
    specs: [{ name: '采购方式', values: ['企业询价', '批量采购'] }],
    tags: ['家居家纺', '待报价'],
    shareTitle: '舒适床品套件',
    shareDesc: '家居家纺精选，适合福利采购。',
  },
  {
    id: 105,
    categoryId: 5,
    name: '精铁炒锅',
    description: '实用炒锅适合家庭日用、员工福利和积分礼品。',
    price: 0,
    originalPrice: undefined,
    coverImage: '/static/products/zk-05.jpg',
    images: ['/static/products/zk-05.jpg'],
    stock: 0,
    sales: 0,
    specs: [{ name: '采购方式', values: ['企业询价', '批量采购'] }],
    tags: ['厨具餐具', '锅具'],
    shareTitle: '精铁炒锅',
    shareDesc: '厨具锅具精选，适合企业福利。',
  },
  {
    id: 106,
    categoryId: 5,
    name: '不锈钢蒸锅',
    description: '不锈钢蒸锅适合居家厨房、节日福利和礼品兑换。',
    price: 0,
    originalPrice: undefined,
    coverImage: '/static/products/zk-06.jpg',
    images: ['/static/products/zk-06.jpg'],
    stock: 0,
    sales: 0,
    specs: [{ name: '采购方式', values: ['企业询价', '批量采购'] }],
    tags: ['厨具餐具', '锅具'],
    shareTitle: '不锈钢蒸锅',
    shareDesc: '厨房实用礼品，适合批量采购。',
  },
  {
    id: 107,
    categoryId: 6,
    name: '商务双肩包',
    description: '商务通勤双肩包适合会议礼赠、员工入职和客户活动。',
    price: 0,
    originalPrice: undefined,
    coverImage: '/static/products/zk-07.jpg',
    images: ['/static/products/zk-07.jpg'],
    stock: 0,
    sales: 0,
    specs: [{ name: '采购方式', values: ['企业询价', '批量采购'] }],
    tags: ['商务箱包', '待报价'],
    shareTitle: '商务双肩包',
    shareDesc: '商务箱包精选，适合企业礼赠。',
  },
  {
    id: 108,
    categoryId: 5,
    name: '多功能电煮锅',
    description: '多功能电煮锅适合宿舍、办公室和居家轻烹饪场景。',
    price: 0,
    originalPrice: undefined,
    coverImage: '/static/products/zk-08.jpg',
    images: ['/static/products/zk-08.jpg'],
    stock: 0,
    sales: 0,
    specs: [{ name: '采购方式', values: ['企业询价', '批量采购'] }],
    tags: ['小家电', '待报价'],
    shareTitle: '多功能电煮锅',
    shareDesc: '小家电精选，适合福利礼品。',
  },
];

export const demoUser = {
  id: 420037,
  openid: 'demo_openid',
  nickname: '企业选品账号',
  phone: '136****2694',
  avatar: '',
  points: 0,
  level: '企业会员',
  cartCount: 0,
  favoriteCount: 0,
  footprintCount: 1,
};

export function getDemoProduct(id: number) {
  return demoProducts.find((item) => item.id === id) || demoProducts[0];
}
